### ISSUE TITLE
PR fails dockerhub job

### ISSUE THREAD

**Issue by jayvdb** [lpenz/ghaction-cmake#16]
As credentials are not provided to the PRs, my PR https://github.com/lpenz/ghaction-cmake/pull/14 is failing all of the dockerhub jobs.

This can be easily bypassed with
```yaml
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index f2c8259..eca9bf7 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,6 +37,7 @@ jobs:
           preset: ${{ matrix.preset }}
           working-directory: execpermfix
   dockerhub:
+    if: github.event_name != 'pull_request'
     needs: [ omnilint, test ]
     runs-on: ubuntu-latest
     strategy:
```

An alternative is to adjust the job so it builds first, and then for PRs skips the step which does the login & push.  However this is a lot of work happening and then discarded.  It provides a tiny bit more QA for a very large cost.
Happy to put up a PR for each approach.  Will do the former if you dont have a strong opinion.
